# Adapted from: https://github.com/james-willett/mkdocs-material-youtube-tutorial

site_name: Cameron Candau
site_url: https://cameroncandau.com
theme:
  favicon: images/favicon.png
  name: material
  features:
    #- navigation.tabs
    #- navigation.sections
    #- toc.integrate
    #- navigation.top
    #- search.suggest
    #- search.highlight
    #- content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep_purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep_purple
      accent: purple

plugins:
  - social
  #- search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Cam-Can-Do
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cameron-candau/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Cameron Candau</a>